language: php

php:
  - 7.4
  
services:
  - mysql
  
addons:
  chrome: stable
 
install:
  - cp .env.travis .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
 
before_script:
  - mysql -e 'create database laravel;'
  - php artisan dusk:chrome-driver
  - php artisan dusk:update
  - php artisan key:generate
  - google-chrome-stable --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  
script:
  - vendor/bin/phpunit
  - php artisan dusk tests/Browser/AdsTest.php
  - php artisan dusk tests/Browser/CommentTest.php
  - php artisan dusk tests/Browser/FollowTest.php
  - php artisan dusk tests/Browser/LikeTest.php
  - php artisan dusk tests/Browser/PostTest.php
