language: php

php:
  - 7.4
  
services:
  - mysql
  
addons:
  chrome: stable
  
before_script:
  - cp .env.travis .env
  - mysql -e 'create database laravel;'
  - composer self-update
  - composer install --no-interaction
  - php artisan dusk:chrome-driver
  - php artisan key:generate
  - cp .env .env.dusk.local
  - google-chrome-stable --headless --disable-gpu http://localhost &
  - php artisan serve &
  
script:
  - vendor/bin/phpunit
  - php artisan dusk
